### ISSUE TITLE
Drifting from binary compatibility with `defaults` on OSX (upgrade to 0.19.8?)

### ISSUE THREAD

**Issue by pkgw** [conda-forge/gettext-feedstock#4]
Some of my packages are having problems on OSX because they require the `libintl.8.dylib`, which is provided by this package, but `defaults` is providing `libintl.9.dylib` as of version 0.19.8. So if you try to install one of these packages, `conda` prefers the `defaults` version of `gettext` and the required shared library is missing.

This might just be solvable by upgrading to 0.19.8 to start providing the new version of `libintl` — although I think we would also need to create a new package version pin to try to start tracking the shared library version dependency more carefully.

**Comment by epruesse** [comment]
The 0.19.8 was broken. Upstream had accidentally bumped the `current` rather than the `revision`, leading to an increase in the so-name version from 8 to 9. This was reverted in 0.19.8.1. Things are working on OSX, because the 0.19.8.1 package is available there, whereas the Linux build seems to have failed.

**Please do not bump to 0.19.8 -- it is broken. Just fix the 0.19.8.1 Linux build**

It's worth considering to manually put in a symlink faking the  `libintl.9.dylib` and `libintl.so.9`, to keep linking issues from happening with packages built using the broken version. I do hope that upstream will skip the so-version 9. 

It's also worth considering to provide `libintl8` style packages using `outputs`. That way this mess doesn't repeat as easily. If at any time they do actually put out a new version, we end up in pinning hell again.

**Comment by pkgw** [comment]
I *think* this problem has worked itself out.
